name: app_engine_core
description: Weather App.
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animate_do: ^3.0.0
  another_flushbar: ^1.12.30
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  geolocator: ^10.0.1
  http: ^1.1.0
  liquid_pull_to_refresh: ^3.0.1
  local_auth: ^2.1.7
  lottie: ^2.6.0
  permission_handler: ^11.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/png/
    - assets/animations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
